### ISSUE TITLE
docker machine learning  - osx

### ISSUE THREAD

**Issue by johndpope** [lgraesser/Neural-Networks-Workshop-Materials-WiMLDS#1]
https://hub.docker.com/r/floydhub/dl-docker/

**Comment by johndpope** [comment]
I created this gist that combines above commands

import thing is to note that docker is running.
<img width="339" alt="screen shot 2017-01-08 at 23 14 39" src="https://cloud.githubusercontent.com/assets/289994/21757103/01231e8e-d5f8-11e6-9adc-a6163766ec1b.png">
https://gist.github.com/johndpope/97c41356639e7add93dd3c05c8f7da8f

**Comment by lgraesser** [comment]
Hi John, 

Thanks for the info re. docker!

In the end I decided to go with virtual environments but this is good to know for the future.

Hope you have a good week.

Best,
Laura
